#!/bin/bash

OPTIND=1 

Help(){
  echo -e "\033[1;32mCuser\033[0m, version 1.0\n"
  echo -e "  Sintaxis: cuser -n <nombre> -g <grupo> -s <shell> -m\n"
  echo "  -h      mostrar ayuda"
  echo "  -n      nombre de usuario"
  echo "  -m      crear directorio en /home"
  echo "  -g      grupos"
  echo "  -s      seleccionar shell"
  echo -e "\n"
}


if [[ -z $* ]]; then
  echo  "   ______ __  __ _____  ______ ____  "
  echo  "  / ____// / / // ___/ / ____// __ \ "
  echo  " / /    / / / / \__ \ / __/  / /_/ / "
  echo  "/ /___ / /_/ / ___/ // /___ / _, _/  "
  echo  "\____/ \____/ /____//_____//_/ |_|   "
  echo -e "\n"

  i=1

  while [[ $i -gt 0 ]]; do

  done

  exit 1
fi


while getopts "hn:g:s:mv" opt; do
  case ${opt} in
    h)
      Help
      exit 1
      ;;
    n)
      nombre=${OPTARG}
      ;;
    g)
      grupos=${OPTARG}
      ;;
    s)
      shell=${OPTARG}
      ;;
    m)
      homeDir=1
      ;;
  esac
done


if [[ -z $nombre ]]; then
  echo -e "\e[1;31mError:\e[0m No se introdujo un nombre de usuario"
else
  if [[ $homeDir == 1 ]]; then
    useradd -m -G $grupos -s $shell $nombre
    echo -e "Usuario creado: \e[1;32m$nombre\e[0m \nAgregado a grupo(s): \e[1;33m$grupos\e[0m \nDirectorio en /home: Si \nShell:$shell"
  else
    useradd -G $grupos -s $shell $nombre
    echo -e "Usuario creado: \e[1;32m$nombre\e[0m \nAgregado a grupo(s): \e[1;33m$grupos\e[0m \nDirectorio en /home: No \nShell:$shell"
  fi

fi


